onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_final_dlx/clk
add wave -noupdate /tb_final_dlx/rst
add wave -noupdate /tb_final_dlx/dlx_instance/clk
add wave -noupdate /tb_final_dlx/dlx_instance/rst
add wave -noupdate /tb_final_dlx/dlx_instance/dram_rd_i
add wave -noupdate /tb_final_dlx/dlx_instance/dram_wr_i
add wave -noupdate /tb_final_dlx/dlx_instance/dram_add_i
add wave -noupdate /tb_final_dlx/dlx_instance/dram_din_i
add wave -noupdate /tb_final_dlx/dlx_instance/dram_dout_i
add wave -noupdate -radix unsigned /tb_final_dlx/dlx_instance/iram_addr_i
add wave -noupdate /tb_final_dlx/dlx_instance/iram_dout_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/clk
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/rst
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dram_rd
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dram_wr
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dram_add
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dram_din
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dram_dout
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/iram_addr
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/iram_dout
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/ir
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/pc
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/in_npc
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/out_npc
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/npc2
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/sel_bus_pc
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/jump_verified
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/comp_branch_dp
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/out_alu_dp
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/pc_bus
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/ir_latch_en_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/npc1_latch_en_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/npc2_latch_en_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/rega_latch_en_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/regb_latch_en_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/regimm_latch_en_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/regaluopcodegen_en_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/en_rd1_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/en_rd2_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/rd1_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/rd2_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/wr_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/wr_cu
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/eq_cond_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/jump_en_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/write_stop_if_branch_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/stop_write
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/muxa_sel_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/muxb_sel_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/alu_outreg_en_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/return_reg_en_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/b2_en_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dram_we_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/lmd_latch_en_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/pc_latch_en_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/wb_mux_sel_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/wb_mux_add_sel_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/rf_we_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/en_rd3_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/alu_outreg2_en_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/sel_alu_ret_i
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/immediate
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/pc_jump
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/rd1
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/rd2
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/wr
add wave -noupdate -radix unsigned /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/add_wr
add wave -noupdate -radix unsigned /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/add_rd1
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/add_rd2
add wave -noupdate -radix unsigned -expand -subitemconfig {/tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(0) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(1) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(2) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(3) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(4) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(5) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(6) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(7) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(8) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(9) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(10) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(11) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(12) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(13) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(14) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(15) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(16) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(17) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(18) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(19) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(20) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(21) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(22) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(23) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(24) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(25) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(26) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(27) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(28) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(29) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(30) {-height 15 -radix unsigned} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers(31) {-height 15 -radix unsigned}} /tb_final_dlx/dlx_instance/dlx_component/dp_i/rf/registers
add wave -noupdate /tb_final_dlx/dlx_instance/memoria_dati/dram_mem
add wave -noupdate /tb_final_dlx/dlx_instance/memoria_istruzioni/iram_mem
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dp_i/b2
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dp_i/din_mem
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dp_i/ir_dp
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dp_i/signal_rd_in
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dp_i/out_rd1
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dp_i/out_rd2
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dp_i/rd3
add wave -noupdate /tb_final_dlx/dlx_instance/dlx_component/dp_i/add_w_rf
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {3559 ps} 0}
configure wave -namecolwidth 360
configure wave -valuecolwidth 265
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {24491 ps}
